services:
  db:
    image: mariadb:11
    container_name: epitime-db-1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: epitime
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  backend:
    build: ./backend
    container_name: epitime-backend-1
    command: >
      sh -c "
        echo '⏳ Waiting for MariaDB...' &&
        until nc -z db 3306; do sleep 1; done &&
        echo '✅ MariaDB is ready. Starting Django...' &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=epitime
      - DB_USER=root
      - DB_PASSWORD=root


  frontend:
    build: ./frontend
    container_name: epitime-frontend-1
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: ["npm", "start"]
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://backend:8000


volumes:
  mariadb_data:
